### ISSUE TITLE
Out of bounds when checking for internal commands on empty lines

### ISSUE THREAD

**Issue by rgantt** [hpolloni/rdsline#11]
The CLI advertises that statements can be "empty-line" delimited, but there's a problem handling empty lines.

Single-line query, semicolon delimited:

```
> SELECT count(id) FROM resources;
+---------+
|   count |
|---------|
|       4 |
+---------+
```

Empty-line delimited:

```
> SELECT count(id) FROM resources
| 
Traceback (most recent call last):
  File "/usr/local/bin/rdsline", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/site-packages/rdsline/cli.py", line 99, in main
    if line[0] == ".":
IndexError: string index out of range
```

**Comment by hpolloni** [comment]
Fixed in 6110ed241426dcd830e3b0cab3eb43ca54a4b153
